# Default
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

# 기본적으로 활성화할 profile을 local로 설정
spring:
  application:
    name: backend
  profiles:
    active:
      ${SPRING_PROFILES_ACTIVE:local} # 환경 변수 SPRING_PROFILES_ACTIVE가 설정되어 있으면 해당 값을 사용하고, 없으면 local을 사용