name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # main 브랜치에 push 시 실행

jobs:
  deploy:
    name: Build and Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create application-prd.yml
        run: |
          echo "${{ secrets.PRD_YML }}" > ./src/main/resources/application-prd.yml
          echo "application-prd.yml created successfully."

      - name: Build with Gradle (PRD profile)
        run: ./gradlew clean build -x test -Dspring.profiles.active=prd

      - name: Copy jar to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_KEY }}
          source: "build/libs/*.jar"
          target: "/home/ubuntu/app"

      - name: Run app on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_KEY }}
          script: |
            sudo systemctl daemon-reload
            sudo systemctl restart moidot-backend.service
            sudo systemctl status moidot-backend.service --no-pager
